image:
  pullPolicy: IfNotPresent
  repository: jesec/flood
  tag: 4.14.3@sha256:c887dad96b40a37fa86d4d77a409dd06220b849c6a8b7d0e2c3ae6dd033deea3
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
