image:
  pullPolicy: IfNotPresent
  repository: jesec/flood
  tag: 4.8@sha256:029fd802b125a53dd6289776a1793e815d61f8ee33cbb686cfae951a390963fe
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
