image:
  pullPolicy: IfNotPresent
  repository: xhofe/alist-aria2
  tag: v3.41.0@sha256:573e8862f6893804fd4a98781e269459f0d69fa148ede371afd2bf58a2dda289
persistence:
  data:
    enabled: true
    mountPath: /opt/alist/data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  aria2:
    enabled: true
    ports:
      aria2:
        enabled: true
        port: 6800
        protocol: http
        targetPort: 6800
  main:
    ports:
      main:
        port: 10167
        protocol: http
        targetPort: 5244
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
