image:
  pullPolicy: IfNotPresent
  repository: jesec/flood
  tag: 4.13.7@sha256:5015664a7a4f1f4b78dc87188b46d8dfbecfa4723f68f1e7e465cdc09a40388d
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
