image:
  pullPolicy: IfNotPresent
  repository: gotson/komga
  tag: 1.15.1@sha256:800b11aed7631888a071c12c138f7a6eef34cfc6878bc624ecf0989f93c741d6
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10085
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: '{{ .Values.service.main.ports.main.port }}'
          probes:
            liveness:
              path: /actuator/health
              port: '{{ .Values.service.main.ports.main.port }}'
            readiness:
              path: /actuator/health
              port: '{{ .Values.service.main.ports.main.port }}'
            startup:
              port: '{{ .Values.service.main.ports.main.port }}'
              type: tcp
