image:
  pullPolicy: IfNotPresent
  repository: docker.io/filebrowser/filebrowser
  tag: v2.63.4@sha256:69131aef9a415cbb0d62ada500ffdfbfe1a535ab860b429fd360676c00f84d1b
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
  database:
    enabled: true
    mountPath: /database
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10187
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FB_ADDRESS: ''
            FB_BASEURL: ''
            FB_CONFIG: /config/filebrowser.json
            FB_DATABASE: /database/filebrowser.db
            FB_PORT: '{{ .Values.service.main.ports.main.port }}'
            FB_ROOT: /data
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
