image:
  pullPolicy: IfNotPresent
  repository: gotson/komga
  tag: 1.23.0@sha256:094dc0825d37950fef0132103bb4309b0e2fc38cdc90955b73528512be62ca59
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10085
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: '{{ .Values.service.main.ports.main.port }}'
          probes:
            liveness:
              path: /actuator/health
              port: '{{ .Values.service.main.ports.main.port }}'
            readiness:
              path: /actuator/health
              port: '{{ .Values.service.main.ports.main.port }}'
            startup:
              port: '{{ .Values.service.main.ports.main.port }}'
              type: tcp
