image:
  pullPolicy: IfNotPresent
  repository: docker.io/filebrowser/filebrowser
  tag: v2.34.2@sha256:0244defba61b8557096cb0d3974b67bd36bbaf1a14e9dd77d1a8f3e3498317e5
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
  database:
    enabled: true
    mountPath: /database
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10187
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FB_ADDRESS: ''
            FB_BASEURL: ''
            FB_CONFIG: /config/filebrowser.json
            FB_DATABASE: /database/filebrowser.db
            FB_PORT: '{{ .Values.service.main.ports.main.port }}'
            FB_ROOT: /data
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
