image:
  pullPolicy: IfNotPresent
  repository: deluan/navidrome
  tag: 0.63.1@sha256:7c43af9f651654e97278be871705aae85a4ee0fa4b310337989699a8ada9b3ed
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_ENABLETRANSCODINGCONFIG: false
            ND_LOGLEVEL: info
            ND_MUSICFOLDER: /music
            ND_SCANSCHEDULE: '@every 15m'
            ND_SESSIONTIMEOUT: 24h
