image:
  pullPolicy: IfNotPresent
  repository: docker.io/filebrowser/filebrowser
  tag: v2.61.0@sha256:9ebcbf84ab4be44e915f2643df9a1c9b9616cd02b72be3f7735cf94e253da3f2
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
  database:
    enabled: true
    mountPath: /database
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10187
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FB_ADDRESS: ''
            FB_BASEURL: ''
            FB_CONFIG: /config/filebrowser.json
            FB_DATABASE: /database/filebrowser.db
            FB_PORT: '{{ .Values.service.main.ports.main.port }}'
            FB_ROOT: /data
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
