image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/onedr0p/qbittorrent
  tag: 5.0.4@sha256:17e3e5f1c7e7fe81434f9d1f5f2e00da9a67f6dbfda1c988c0619932cb856047
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
qbitportforward:
  QBT_PASSWORD: adminadmin
  QBT_USERNAME: admin
  enabled: false
qbitportforwardImage:
  pullPolicy: IfNotPresent
  repository: docker.io/mjmeli/qbittorrent-port-forward-gluetun-server
  tag: latest@sha256:67d0d21ed792cf80716d4211e7162b6d375af5c12f3cf096c9032ad705dddaa8
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  gluetun:
    enabled: true
    ports:
      gluetun:
        enabled: true
        port: 8000
        protocol: http
        targetPort: 8000
    type: ClusterIP
  main:
    ports:
      main:
        port: 10095
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
        protocol: tcp
      torrentudp:
        enabled: true
        port: '{{ .Values.service.torrent.ports.torrent.port }}'
        protocol: udp
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            QBT_TORRENTING_PORT: '{{ .Values.service.torrent.ports.torrent.port }}'
            QBT_WEBUI_PORT: '{{ .Values.service.main.ports.main.port }}'
  qbitportforward:
    enabled: true
    podSpec:
      containers:
        qbitportforward:
          command: /usr/src/app/main.sh
          enabled: true
          env:
            GTN_ADDR: '{{ printf "http://%v-gluetun:8000" (include "tc.v1.common.lib.chart.names.fullname"
              $) }}'
            QBT_ADDR: '{{ printf "http://%v:%v" (include "tc.v1.common.lib.chart.names.fullname"
              $) .Values.service.main.ports.main.port }}'
            QBT_PASSWORD: '{{ .Values.qbitportforward.QBT_PASSWORD }}'
            QBT_USERNAME: '{{ .Values.qbitportforward.QBT_USERNAME }}'
          imageSelector: qbitportforwardImage
          primary: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
      restartPolicy: OnFailure
    schedule: '*/5 * * * *'
    type: CronJob
