image:
  pullPolicy: IfNotPresent
  repository: docker.io/filebrowser/filebrowser
  tag: v2.40.0@sha256:feedeba4f2a8c6b3a6191647a4e31ee6b925123db4feae04a251343674497908
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
  database:
    enabled: true
    mountPath: /database
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10187
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FB_ADDRESS: ''
            FB_BASEURL: ''
            FB_CONFIG: /config/filebrowser.json
            FB_DATABASE: /database/filebrowser.db
            FB_PORT: '{{ .Values.service.main.ports.main.port }}'
            FB_ROOT: /data
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
