image:
  pullPolicy: IfNotPresent
  repository: jesec/flood
  tag: 4.15.0@sha256:26e66e480ca7a044ad8cd4ac191c2967db2e5eaf584a0d749b83fd0a230b7fc4
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
