image:
  pullPolicy: IfNotPresent
  repository: jesec/flood
  tag: 4.16.0@sha256:81582c74eba5b787d686c1669b9c4651d88472988e960aafeacd7fd70cdd1dd5
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
