image:
  pullPolicy: IfNotPresent
  repository: gotson/komga
  tag: 1.23.5@sha256:85f0be8920742341217f2b2bdafef64da1f6062ae472dcf74426a9fa549c8a05
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10085
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: '{{ .Values.service.main.ports.main.port }}'
          probes:
            liveness:
              path: /actuator/health
              port: '{{ .Values.service.main.ports.main.port }}'
            readiness:
              path: /actuator/health
              port: '{{ .Values.service.main.ports.main.port }}'
            startup:
              port: '{{ .Values.service.main.ports.main.port }}'
              type: tcp
