image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/wg-easy/wg-easy
  tag: 14@sha256:5f26407fd2ede54df76d63304ef184576a6c1bb73f934a58a11abdd852fab549
persistence:
  config:
    enabled: true
    mountPath: /etc/wireguard
portal:
  open:
    enabled: true
securityContext:
  container:
    PUID: 0
    capabilities:
      add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 51821
  vpn:
    enabled: true
    ports:
      vpn:
        enabled: true
        port: 51820
        protocol: udp
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LANG: en
            PASSWORD: secretpass
            PORT: '{{ .Values.service.main.ports.main.port }}'
            UI_TRAFFIC_STATS: 'false'
            WG_ALLOWED_IPS: 0.0.0.0/0, ::/0
            WG_DEFAULT_ADDRESS: 10.8.0.x
            WG_DEFAULT_DNS: 1.1.1.1
            WG_HOST: localhost
            WG_MTU: 0
            WG_PERSISTENT_KEEPALIVE: 0
            WG_PORT: '{{ .Values.service.vpn.ports.vpn.port }}'
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
