name: Update Helm Catalog

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write  # Ensure the workflow can push to main

jobs:
  update-catalog:
    name: Update Helm Catalog
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".updater/pyproject.toml"
      
      - name: Install dependencies
        working-directory: .updater
        run: uv sync
      
      - name: Run update script
        working-directory: .updater
        run: uv run python update.py
        continue-on-error: false
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git rev-list --count origin/main..HEAD) -ne 0 ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Found changes to push"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes to push"
          fi
      
      - name: Push changes to main
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git push origin main
