image:
  pullPolicy: IfNotPresent
  repository: deluan/navidrome
  tag: 0.62.0@sha256:c4b5cb36a790b3eb63ca6a68bbe2fe149c2d7fa2e586f7a480e61db630e6664b
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_ENABLETRANSCODINGCONFIG: false
            ND_LOGLEVEL: info
            ND_MUSICFOLDER: /music
            ND_SCANSCHEDULE: '@every 15m'
            ND_SESSIONTIMEOUT: 24h
